require 'synthesizer/modulation/curve'
require 'synthesizer/modulation/releasable_envelope'
require 'synthesizer/modulation/adsr'
require 'synthesizer/modulation/dx7_envelope'
require 'synthesizer/modulation/lfo'
require 'synthesizer/modulation/glide'
