require 'synthesizer/modulation/curve'
require 'synthesizer/modulation/amp_envelope'
require 'synthesizer/modulation/adsr'
require 'synthesizer/modulation/dx7_envelope'
require 'synthesizer/modulation/dx7_pitch_envelope'
require 'synthesizer/modulation/lfo'
require 'synthesizer/modulation/glide'
